using EAP.Entity.Models.Address;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EAP.Entity.Configurations
{
    public class DistrictsConfiguration : IEntityTypeConfiguration<Districts>
    {
        public void Configure(EntityTypeBuilder<Districts> builder)
        {
            builder.HasData(
                new Districts { Id = 1, StateId = 1, DistrictName = "Bhojpur", DistrictCode = "" },
                new Districts { Id = 2, StateId = 1, DistrictName = "Dhankuta", DistrictCode = "" },
                new Districts { Id = 3, StateId = 1, DistrictName = "Ilam", DistrictCode = "" },
                new Districts { Id = 4, StateId = 1, DistrictName = "Jhapa", DistrictCode = "" },
                new Districts { Id = 5, StateId = 1, DistrictName = "Khotang", DistrictCode = "" },
                new Districts { Id = 6, StateId = 1, DistrictName = "Morang", DistrictCode = "" },
                new Districts { Id = 7, StateId = 1, DistrictName = "Okhaldhunga", DistrictCode = "" },
                new Districts { Id = 8, StateId = 1, DistrictName = "Panchthar", DistrictCode = "" },
                new Districts { Id = 9, StateId = 1, DistrictName = "Sankhuwasabha", DistrictCode = "" },
                new Districts { Id = 10, StateId = 1, DistrictName = "Solukhumbu", DistrictCode = "" },
                new Districts { Id = 11, StateId = 1, DistrictName = "Sunsari", DistrictCode = "" },
                new Districts { Id = 12, StateId = 1, DistrictName = "Taplejung", DistrictCode = "" },
                new Districts { Id = 13, StateId = 1, DistrictName = "Terhathum", DistrictCode = "" },
                new Districts { Id = 14, StateId = 1, DistrictName = "Udayapur", DistrictCode = "" },
                new Districts { Id = 15, StateId = 2, DistrictName = "Saptari", DistrictCode = "" },
                new Districts { Id = 16, StateId = 2, DistrictName = "Siraha", DistrictCode = "" },
                new Districts { Id = 17, StateId = 2, DistrictName = "Dhanusa", DistrictCode = "" },
                new Districts { Id = 18, StateId = 2, DistrictName = "Mahottari", DistrictCode = "" },
                new Districts { Id = 19, StateId = 2, DistrictName = "Sarlahi", DistrictCode = "" },
                new Districts { Id = 20, StateId = 2, DistrictName = "Bara", DistrictCode = "" },
                new Districts { Id = 21, StateId = 2, DistrictName = "Parsa", DistrictCode = "" },
                new Districts { Id = 22, StateId = 2, DistrictName = "Rautahat", DistrictCode = "" },
                new Districts { Id = 23, StateId = 3, DistrictName = "Sindhuli", DistrictCode = "" },
                new Districts { Id = 24, StateId = 3, DistrictName = "Ramechhap", DistrictCode = "" },
                new Districts { Id = 25, StateId = 3, DistrictName = "Dolakha", DistrictCode = "" },
                new Districts { Id = 26, StateId = 3, DistrictName = "Bhaktapur", DistrictCode = "" },
                new Districts { Id = 27, StateId = 3, DistrictName = "Dhading", DistrictCode = "" },
                new Districts { Id = 28, StateId = 3, DistrictName = "Kathmandu", DistrictCode = "" },
                new Districts { Id = 29, StateId = 3, DistrictName = "Kavrepalanchok", DistrictCode = "" },
                new Districts { Id = 30, StateId = 3, DistrictName = "Lalitpur", DistrictCode = "" },
                new Districts { Id = 31, StateId = 3, DistrictName = "Nuwakot", DistrictCode = "" },
                new Districts { Id = 32, StateId = 3, DistrictName = "Rasuwa", DistrictCode = "" },
                new Districts { Id = 33, StateId = 3, DistrictName = "Sindhupalchok", DistrictCode = "" },
                new Districts { Id = 34, StateId = 3, DistrictName = "Chitwan", DistrictCode = "" },
                new Districts { Id = 35, StateId = 3, DistrictName = "Makwanpur", DistrictCode = "" },
                new Districts { Id = 36, StateId = 4, DistrictName = "Baglung", DistrictCode = "" },
                new Districts { Id = 37, StateId = 4, DistrictName = "Gorkha", DistrictCode = "" },
                new Districts { Id = 38, StateId = 4, DistrictName = "Kaski", DistrictCode = "" },
                new Districts { Id = 39, StateId = 4, DistrictName = "Lamjung", DistrictCode = "" },
                new Districts { Id = 40, StateId = 4, DistrictName = "Manang", DistrictCode = "" },
                new Districts { Id = 41, StateId = 4, DistrictName = "Mustang", DistrictCode = "" },
                new Districts { Id = 42, StateId = 4, DistrictName = "Myagdi", DistrictCode = "" },
                new Districts { Id = 43, StateId = 4, DistrictName = "Nawalpur", DistrictCode = "" },
                new Districts { Id = 44, StateId = 4, DistrictName = "Parbat", DistrictCode = "" },
                new Districts { Id = 45, StateId = 4, DistrictName = "Syangja", DistrictCode = "" },
                new Districts { Id = 46, StateId = 4, DistrictName = "Tanahun", DistrictCode = "" },
                new Districts { Id = 47, StateId = 5, DistrictName = "Kapilvastu", DistrictCode = "" },
                new Districts { Id = 48, StateId = 5, DistrictName = "Parasi", DistrictCode = "" },
                new Districts { Id = 49, StateId = 5, DistrictName = "Rupandehi", DistrictCode = "" },
                new Districts { Id = 50, StateId = 5, DistrictName = "Arghakhanchi", DistrictCode = "" },
                new Districts { Id = 51, StateId = 5, DistrictName = "Gulmi", DistrictCode = "" },
                new Districts { Id = 52, StateId = 5, DistrictName = "Palpa", DistrictCode = "" },
                new Districts { Id = 53, StateId = 5, DistrictName = "Dang", DistrictCode = "" },
                new Districts { Id = 54, StateId = 5, DistrictName = "Pyuthan", DistrictCode = "" },
                new Districts { Id = 55, StateId = 5, DistrictName = "Rolpa", DistrictCode = "" },
                new Districts { Id = 56, StateId = 5, DistrictName = "Eastern Rukum", DistrictCode = "" },
                new Districts { Id = 57, StateId = 5, DistrictName = "Banke", DistrictCode = "" },
                new Districts { Id = 58, StateId = 5, DistrictName = "Bardiya", DistrictCode = "" },
                new Districts { Id = 59, StateId = 6, DistrictName = "Western Rukum", DistrictCode = "" },
                new Districts { Id = 60, StateId = 6, DistrictName = "Salyan", DistrictCode = "" },
                new Districts { Id = 61, StateId = 6, DistrictName = "Dolpa", DistrictCode = "" },
                new Districts { Id = 62, StateId = 6, DistrictName = "Humla", DistrictCode = "" },
                new Districts { Id = 63, StateId = 6, DistrictName = "Jumla", DistrictCode = "" },
                new Districts { Id = 64, StateId = 6, DistrictName = "Kalikot", DistrictCode = "" },
                new Districts { Id = 65, StateId = 6, DistrictName = "Mugu", DistrictCode = "" },
                new Districts { Id = 66, StateId = 6, DistrictName = "Surkhet", DistrictCode = "" },
                new Districts { Id = 67, StateId = 6, DistrictName = "Dailekh", DistrictCode = "" },
                new Districts { Id = 68, StateId = 6, DistrictName = "Jajarkot", DistrictCode = "" },
                new Districts { Id = 69, StateId = 7, DistrictName = "Kailali", DistrictCode = "" },
                new Districts { Id = 70, StateId = 7, DistrictName = "Achham", DistrictCode = "" },
                new Districts { Id = 71, StateId = 7, DistrictName = "Doti", DistrictCode = "" },
                new Districts { Id = 72, StateId = 7, DistrictName = "Bajhang", DistrictCode = "" },
                new Districts { Id = 73, StateId = 7, DistrictName = "Bajura", DistrictCode = "" },
                new Districts { Id = 74, StateId = 7, DistrictName = "Kanchanpur", DistrictCode = "" },
                new Districts { Id = 75, StateId = 7, DistrictName = "Dadeldhura", DistrictCode = "" },
                new Districts { Id = 76, StateId = 7, DistrictName = "Baitadi", DistrictCode = "" },
                new Districts { Id = 77, StateId = 7, DistrictName = "Darchula", DistrictCode = "" }
                );
        }
    }
}