// <auto-generated />
using EAP.Entity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EAP.API.Migrations
{
    [DbContext(typeof(EAPDbContext))]
    partial class EAPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EAP.Entity.Models.Address.States", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StateId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("States", "Address");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 152,
                            StateName = "Province No. 1"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 152,
                            StateName = "Province No. 2"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 152,
                            StateName = "Province No. 3"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 152,
                            StateName = "Gandaki"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 152,
                            StateName = "Province No. 5"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 152,
                            StateName = "Karnali"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 152,
                            StateName = "PSudurpashchim"
                        });
                });

            modelBuilder.Entity("EAP.Entity.Models.Country.Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CountryName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Countries", "Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF",
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AX",
                            CountryName = "Åland Islands"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AL",
                            CountryName = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DZ",
                            CountryName = "Algeria"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AS",
                            CountryName = "American Samoa"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AD",
                            CountryName = "AndorrA"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AO",
                            CountryName = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AQ",
                            CountryName = "Antarctica"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AG",
                            CountryName = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AR",
                            CountryName = "Argentina"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AM",
                            CountryName = "Armenia"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AW",
                            CountryName = "Aruba"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AU",
                            CountryName = "Australia"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AT",
                            CountryName = "Austria"
                        },
                        new
                        {
                            Id = 15,
                            Code = "AZ",
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BS",
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BH",
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BD",
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BB",
                            CountryName = "Barbados"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BY",
                            CountryName = "Belarus"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BE",
                            CountryName = "Belgium"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BZ",
                            CountryName = "Belize"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BJ",
                            CountryName = "Benin"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BM",
                            CountryName = "Bermuda"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BT",
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BO",
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BA",
                            CountryName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BW",
                            CountryName = "Botswana"
                        },
                        new
                        {
                            Id = 29,
                            Code = "BV",
                            CountryName = "Bouvet Island"
                        },
                        new
                        {
                            Id = 30,
                            Code = "BR",
                            CountryName = "Brazil"
                        },
                        new
                        {
                            Id = 31,
                            Code = "IO",
                            CountryName = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 32,
                            Code = "BN",
                            CountryName = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 33,
                            Code = "BG",
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            Id = 34,
                            Code = "BF",
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            Id = 35,
                            Code = "BI",
                            CountryName = "Burundi"
                        },
                        new
                        {
                            Id = 36,
                            Code = "KH",
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            Id = 37,
                            Code = "CM",
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            Id = 38,
                            Code = "CA",
                            CountryName = "Canada"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CV",
                            CountryName = "Cape Verde"
                        },
                        new
                        {
                            Id = 40,
                            Code = "KY",
                            CountryName = "Cayman Islands"
                        },
                        new
                        {
                            Id = 41,
                            Code = "CF",
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            Id = 42,
                            Code = "TD",
                            CountryName = "Chad"
                        },
                        new
                        {
                            Id = 43,
                            Code = "CL",
                            CountryName = "Chile"
                        },
                        new
                        {
                            Id = 44,
                            Code = "CN",
                            CountryName = "China"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CX",
                            CountryName = "Christmas Island"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CC",
                            CountryName = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 47,
                            Code = "CO",
                            CountryName = "Colombia"
                        },
                        new
                        {
                            Id = 48,
                            Code = "KM",
                            CountryName = "Comoros"
                        },
                        new
                        {
                            Id = 49,
                            Code = "CG",
                            CountryName = "Congo"
                        },
                        new
                        {
                            Id = 50,
                            Code = "CD",
                            CountryName = "Congo, The Democratic Republic of the"
                        },
                        new
                        {
                            Id = 51,
                            Code = "CK",
                            CountryName = "Cook Islands"
                        },
                        new
                        {
                            Id = 52,
                            Code = "CR",
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            Id = 53,
                            Code = "CI",
                            CountryName = "Cote D'Ivoire"
                        },
                        new
                        {
                            Id = 54,
                            Code = "HR",
                            CountryName = "Croatia"
                        },
                        new
                        {
                            Id = 55,
                            Code = "CU",
                            CountryName = "Cuba"
                        },
                        new
                        {
                            Id = 56,
                            Code = "CY",
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            Id = 57,
                            Code = "CZ",
                            CountryName = "Czech Republic"
                        },
                        new
                        {
                            Id = 58,
                            Code = "DK",
                            CountryName = "Denmark"
                        },
                        new
                        {
                            Id = 59,
                            Code = "DJ",
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            Id = 60,
                            Code = "DM",
                            CountryName = "Dominica"
                        },
                        new
                        {
                            Id = 61,
                            Code = "DO",
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            Id = 62,
                            Code = "EC",
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            Id = 63,
                            Code = "EG",
                            CountryName = "Egypt"
                        },
                        new
                        {
                            Id = 64,
                            Code = "SV",
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            Id = 65,
                            Code = "GQ",
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 66,
                            Code = "ER",
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            Id = 67,
                            Code = "EE",
                            CountryName = "Estonia"
                        },
                        new
                        {
                            Id = 68,
                            Code = "ET",
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            Id = 69,
                            Code = "FK",
                            CountryName = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = 70,
                            Code = "FO",
                            CountryName = "Faroe Islands"
                        },
                        new
                        {
                            Id = 71,
                            Code = "FJ",
                            CountryName = "Fiji"
                        },
                        new
                        {
                            Id = 72,
                            Code = "FI",
                            CountryName = "Finland"
                        },
                        new
                        {
                            Id = 73,
                            Code = "FR",
                            CountryName = "France"
                        },
                        new
                        {
                            Id = 74,
                            Code = "GF",
                            CountryName = "French Guiana"
                        },
                        new
                        {
                            Id = 75,
                            Code = "PF",
                            CountryName = "French Polynesia"
                        },
                        new
                        {
                            Id = 76,
                            Code = "TF",
                            CountryName = "French Southern Territories"
                        },
                        new
                        {
                            Id = 77,
                            Code = "GA",
                            CountryName = "Gabon"
                        },
                        new
                        {
                            Id = 78,
                            Code = "GM",
                            CountryName = "Gambia"
                        },
                        new
                        {
                            Id = 79,
                            Code = "GE",
                            CountryName = "Georgia"
                        },
                        new
                        {
                            Id = 80,
                            Code = "DE",
                            CountryName = "Germany"
                        },
                        new
                        {
                            Id = 81,
                            Code = "GH",
                            CountryName = "Ghana"
                        },
                        new
                        {
                            Id = 82,
                            Code = "GI",
                            CountryName = "Gibraltar"
                        },
                        new
                        {
                            Id = 83,
                            Code = "GR",
                            CountryName = "Greece"
                        },
                        new
                        {
                            Id = 84,
                            Code = "GL",
                            CountryName = "Greenland"
                        },
                        new
                        {
                            Id = 85,
                            Code = "GD",
                            CountryName = "Grenada"
                        },
                        new
                        {
                            Id = 86,
                            Code = "GP",
                            CountryName = "Guadeloupe"
                        },
                        new
                        {
                            Id = 87,
                            Code = "GU",
                            CountryName = "Guam"
                        },
                        new
                        {
                            Id = 88,
                            Code = "GT",
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            Id = 89,
                            Code = "GG",
                            CountryName = "Guernsey"
                        },
                        new
                        {
                            Id = 90,
                            Code = "GN",
                            CountryName = "Guinea"
                        },
                        new
                        {
                            Id = 91,
                            Code = "GW",
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 92,
                            Code = "GY",
                            CountryName = "Guyana"
                        },
                        new
                        {
                            Id = 93,
                            Code = "HT",
                            CountryName = "Haiti"
                        },
                        new
                        {
                            Id = 94,
                            Code = "HM",
                            CountryName = "Heard Island and Mcdonald Islands"
                        },
                        new
                        {
                            Id = 95,
                            Code = "VA",
                            CountryName = "Holy See (Vatican City States)"
                        },
                        new
                        {
                            Id = 96,
                            Code = "HN",
                            CountryName = "Honduras"
                        },
                        new
                        {
                            Id = 97,
                            Code = "HK",
                            CountryName = "Hong Kong"
                        },
                        new
                        {
                            Id = 98,
                            Code = "HU",
                            CountryName = "Hungary"
                        },
                        new
                        {
                            Id = 99,
                            Code = "IS",
                            CountryName = "Iceland"
                        },
                        new
                        {
                            Id = 100,
                            Code = "IN",
                            CountryName = "India"
                        },
                        new
                        {
                            Id = 101,
                            Code = "ID",
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            Id = 102,
                            Code = "IR",
                            CountryName = "Iran, Islamic Republic Of"
                        },
                        new
                        {
                            Id = 103,
                            Code = "IQ",
                            CountryName = "Iraq"
                        },
                        new
                        {
                            Id = 104,
                            Code = "IE",
                            CountryName = "Ireland"
                        },
                        new
                        {
                            Id = 105,
                            Code = "IM",
                            CountryName = "Isle of Man"
                        },
                        new
                        {
                            Id = 106,
                            Code = "IL",
                            CountryName = "Israel"
                        },
                        new
                        {
                            Id = 107,
                            Code = "IT",
                            CountryName = "Italy"
                        },
                        new
                        {
                            Id = 108,
                            Code = "JM",
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            Id = 109,
                            Code = "JP",
                            CountryName = "Japan"
                        },
                        new
                        {
                            Id = 110,
                            Code = "JE",
                            CountryName = "Jersey"
                        },
                        new
                        {
                            Id = 111,
                            Code = "JO",
                            CountryName = "Jordan"
                        },
                        new
                        {
                            Id = 112,
                            Code = "KZ",
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            Id = 113,
                            Code = "KE",
                            CountryName = "Kenya"
                        },
                        new
                        {
                            Id = 114,
                            Code = "KI",
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            Id = 115,
                            Code = "KP",
                            CountryName = "Korea, Democratic People's Republic of"
                        },
                        new
                        {
                            Id = 116,
                            Code = "KR",
                            CountryName = "Korea, Republic of"
                        },
                        new
                        {
                            Id = 117,
                            Code = "KW",
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            Id = 118,
                            Code = "KG",
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 119,
                            Code = "LA",
                            CountryName = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            Id = 120,
                            Code = "LV",
                            CountryName = "Latvia"
                        },
                        new
                        {
                            Id = 121,
                            Code = "LB",
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            Id = 122,
                            Code = "LS",
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            Id = 123,
                            Code = "LR",
                            CountryName = "Liberia"
                        },
                        new
                        {
                            Id = 124,
                            Code = "LY",
                            CountryName = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            Id = 125,
                            Code = "LI",
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            Id = 126,
                            Code = "LT",
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            Id = 127,
                            Code = "LU",
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            Id = 128,
                            Code = "MO",
                            CountryName = "Macao"
                        },
                        new
                        {
                            Id = 129,
                            Code = "MK",
                            CountryName = "Macedonia, The Former Yugoslav Republic of"
                        },
                        new
                        {
                            Id = 130,
                            Code = "MG",
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            Id = 131,
                            Code = "MW",
                            CountryName = "Malawi"
                        },
                        new
                        {
                            Id = 132,
                            Code = "MY",
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            Id = 133,
                            Code = "MV",
                            CountryName = "Maldives"
                        },
                        new
                        {
                            Id = 134,
                            Code = "ML",
                            CountryName = "Mali"
                        },
                        new
                        {
                            Id = 135,
                            Code = "MT",
                            CountryName = "Malta"
                        },
                        new
                        {
                            Id = 136,
                            Code = "MH",
                            CountryName = "Marshall Islands"
                        },
                        new
                        {
                            Id = 137,
                            Code = "MQ",
                            CountryName = "Martinique"
                        },
                        new
                        {
                            Id = 138,
                            Code = "MR",
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            Id = 139,
                            Code = "MU",
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            Id = 140,
                            Code = "YT",
                            CountryName = "Mayotte"
                        },
                        new
                        {
                            Id = 141,
                            Code = "MX",
                            CountryName = "Mexico"
                        },
                        new
                        {
                            Id = 142,
                            Code = "FM",
                            CountryName = "Micronesia, Federated Statess of"
                        },
                        new
                        {
                            Id = 143,
                            Code = "MD",
                            CountryName = "Moldova, Republic of"
                        },
                        new
                        {
                            Id = 144,
                            Code = "MC",
                            CountryName = "Monaco"
                        },
                        new
                        {
                            Id = 145,
                            Code = "MN",
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            Id = 146,
                            Code = "MS",
                            CountryName = "Montserrat"
                        },
                        new
                        {
                            Id = 147,
                            Code = "MA",
                            CountryName = "Morocco"
                        },
                        new
                        {
                            Id = 148,
                            Code = "MZ",
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            Id = 149,
                            Code = "MM",
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            Id = 150,
                            Code = "NA",
                            CountryName = "Namibia"
                        },
                        new
                        {
                            Id = 151,
                            Code = "NR",
                            CountryName = "Nauru"
                        },
                        new
                        {
                            Id = 152,
                            Code = "NP",
                            CountryName = "Nepal"
                        },
                        new
                        {
                            Id = 153,
                            Code = "NL",
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            Id = 154,
                            Code = "AN",
                            CountryName = "Netherlands Antilles"
                        },
                        new
                        {
                            Id = 155,
                            Code = "NC",
                            CountryName = "New Caledonia"
                        },
                        new
                        {
                            Id = 156,
                            Code = "NZ",
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            Id = 157,
                            Code = "NI",
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            Id = 158,
                            Code = "NE",
                            CountryName = "Niger"
                        },
                        new
                        {
                            Id = 159,
                            Code = "NG",
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            Id = 160,
                            Code = "NU",
                            CountryName = "Niue"
                        },
                        new
                        {
                            Id = 161,
                            Code = "NF",
                            CountryName = "Norfolk Island"
                        },
                        new
                        {
                            Id = 162,
                            Code = "MP",
                            CountryName = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 163,
                            Code = "NO",
                            CountryName = "Norway"
                        },
                        new
                        {
                            Id = 164,
                            Code = "OM",
                            CountryName = "Oman"
                        },
                        new
                        {
                            Id = 165,
                            Code = "PK",
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            Id = 166,
                            Code = "PW",
                            CountryName = "Palau"
                        },
                        new
                        {
                            Id = 167,
                            Code = "PS",
                            CountryName = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            Id = 168,
                            Code = "PA",
                            CountryName = "Panama"
                        },
                        new
                        {
                            Id = 169,
                            Code = "PG",
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 170,
                            Code = "PY",
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            Id = 171,
                            Code = "PE",
                            CountryName = "Peru"
                        },
                        new
                        {
                            Id = 172,
                            Code = "PH",
                            CountryName = "Philippines"
                        },
                        new
                        {
                            Id = 173,
                            Code = "PN",
                            CountryName = "Pitcairn"
                        },
                        new
                        {
                            Id = 174,
                            Code = "PN",
                            CountryName = "Poland"
                        },
                        new
                        {
                            Id = 175,
                            Code = "PT",
                            CountryName = "Portugal"
                        },
                        new
                        {
                            Id = 176,
                            Code = "PR",
                            CountryName = "Puerto Rico"
                        },
                        new
                        {
                            Id = 177,
                            Code = "QA",
                            CountryName = "Qatar"
                        },
                        new
                        {
                            Id = 178,
                            Code = "RE",
                            CountryName = "Reunion"
                        },
                        new
                        {
                            Id = 179,
                            Code = "RO",
                            CountryName = "Romania"
                        },
                        new
                        {
                            Id = 180,
                            Code = "RU",
                            CountryName = "Russian Federation"
                        },
                        new
                        {
                            Id = 181,
                            Code = "RW",
                            CountryName = "RWANDA"
                        },
                        new
                        {
                            Id = 182,
                            Code = "SH",
                            CountryName = "Saint Helena"
                        },
                        new
                        {
                            Id = 183,
                            Code = "KN",
                            CountryName = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 184,
                            Code = "LC",
                            CountryName = "Saint Lucia"
                        },
                        new
                        {
                            Id = 185,
                            Code = "PM",
                            CountryName = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 186,
                            Code = "VC",
                            CountryName = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 187,
                            Code = "WS",
                            CountryName = "Samoa"
                        },
                        new
                        {
                            Id = 188,
                            Code = "SM",
                            CountryName = "San Marino"
                        },
                        new
                        {
                            Id = 189,
                            Code = "ST",
                            CountryName = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 190,
                            Code = "SA",
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 191,
                            Code = "SN",
                            CountryName = "Senegal"
                        },
                        new
                        {
                            Id = 192,
                            Code = "CS",
                            CountryName = "Serbia and Montenegro"
                        },
                        new
                        {
                            Id = 193,
                            Code = "SC",
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            Id = 194,
                            Code = "SL",
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            Id = 195,
                            Code = "SG",
                            CountryName = "Singapore"
                        },
                        new
                        {
                            Id = 196,
                            Code = "SK",
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            Id = 197,
                            Code = "SI",
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            Id = 198,
                            Code = "SB",
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            Id = 199,
                            Code = "SO",
                            CountryName = "Somalia"
                        },
                        new
                        {
                            Id = 200,
                            Code = "ZA",
                            CountryName = "South Africa"
                        },
                        new
                        {
                            Id = 201,
                            Code = "GS",
                            CountryName = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 202,
                            Code = "ES",
                            CountryName = "Spain"
                        },
                        new
                        {
                            Id = 203,
                            Code = "LK",
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            Id = 204,
                            Code = "SD",
                            CountryName = "Sudan"
                        },
                        new
                        {
                            Id = 205,
                            Code = "SR",
                            CountryName = "Suriname"
                        },
                        new
                        {
                            Id = 206,
                            Code = "SJ",
                            CountryName = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 207,
                            Code = "SZ",
                            CountryName = "Swaziland"
                        },
                        new
                        {
                            Id = 208,
                            Code = "SE",
                            CountryName = "Sweden"
                        },
                        new
                        {
                            Id = 209,
                            Code = "CH",
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            Id = 210,
                            Code = "SY",
                            CountryName = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = 211,
                            Code = "TW",
                            CountryName = "Taiwan, Province of China"
                        },
                        new
                        {
                            Id = 212,
                            Code = "TJ",
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            Id = 213,
                            Code = "TZ",
                            CountryName = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = 214,
                            Code = "TH",
                            CountryName = "Thailand"
                        },
                        new
                        {
                            Id = 215,
                            Code = "TL",
                            CountryName = "Timor-Leste"
                        },
                        new
                        {
                            Id = 216,
                            Code = "TG",
                            CountryName = "Togo"
                        },
                        new
                        {
                            Id = 217,
                            Code = "TK",
                            CountryName = "Tokelau"
                        },
                        new
                        {
                            Id = 218,
                            Code = "TO",
                            CountryName = "Tonga"
                        },
                        new
                        {
                            Id = 219,
                            Code = "TT",
                            CountryName = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 220,
                            Code = "TN",
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            Id = 221,
                            Code = "TR",
                            CountryName = "Turkey"
                        },
                        new
                        {
                            Id = 222,
                            Code = "TM",
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            Id = 223,
                            Code = "TC",
                            CountryName = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 224,
                            Code = "TV",
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            Id = 225,
                            Code = "UG",
                            CountryName = "Uganda"
                        },
                        new
                        {
                            Id = 226,
                            Code = "UA",
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            Id = 227,
                            Code = "AE",
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 228,
                            Code = "GB",
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            Id = 229,
                            Code = "US",
                            CountryName = "United Statess"
                        },
                        new
                        {
                            Id = 230,
                            Code = "UM",
                            CountryName = "United Statess Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 231,
                            Code = "UY",
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            Id = 232,
                            Code = "UZ",
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            Id = 233,
                            Code = "VU",
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            Id = 234,
                            Code = "VE",
                            CountryName = "Venezuela"
                        },
                        new
                        {
                            Id = 235,
                            Code = "VN",
                            CountryName = "Viet Nam"
                        },
                        new
                        {
                            Id = 236,
                            Code = "VG",
                            CountryName = "Virgin Islands, British"
                        },
                        new
                        {
                            Id = 237,
                            Code = "VI",
                            CountryName = "Virgin Islands, U.S."
                        },
                        new
                        {
                            Id = 238,
                            Code = "WF",
                            CountryName = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 239,
                            Code = "EH",
                            CountryName = "Western Sahara"
                        },
                        new
                        {
                            Id = 240,
                            Code = "YE",
                            CountryName = "Yemen"
                        },
                        new
                        {
                            Id = 241,
                            Code = "ZM",
                            CountryName = "Zambia"
                        },
                        new
                        {
                            Id = 242,
                            Code = "ZW",
                            CountryName = "Zimbabwe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
